Repository AICoE/internal-data-hub, pull requests merged in 2020-11, with the labels that each got.

#17 Move admin password out of grafana file
  grafana/README.md
  grafana/prod/grafana.yaml
  grafana/prod/kustomization.yaml
  grafana/prod/secret-generator.yaml
  grafana/prod/secrets/admin_credentials.enc.yaml
Labels: approved, size/M

#18 Fix pre-commit errors for Grafana
  grafana/prod/grafana.yaml
  grafana/prod/kustomization.yaml
Labels: approved, size/XS

#19 Move rsyslog secret generators
  rsyslog/overlays/prod/kustomization.yaml
  rsyslog/overlays/prod/secrets/secret-generator.yaml
  rsyslog/overlays/stage/kustomization.yaml
  rsyslog/overlays/stage/secrets/secret-generator.yaml
Labels: approved, size/XS

#20 Update Prometheus
  prometheus/bases/prometheus/prometheus.yaml
Labels: approved, size/XS

#22 Add grafana dashboard
  grafana/prod/dashboards/argocd-dashboard.yaml
  grafana/prod/dashboards/kustomization.yaml
  grafana/prod/datasources/datasource.yaml
  grafana/prod/grafana.yaml
  grafana/prod/kustomization.yaml
Labels: approved, size/XXL

#23 Update prom to not require namespace selectors
  prometheus/README.md
  prometheus/bases/prometheus/prometheus.yaml
Labels: approved, size/S

#25 Add ldap auth to grafana
  grafana/README.md
  grafana/prod/configs/ldap.toml
  grafana/prod/grafana.yaml
  grafana/prod/kustomization.yaml
Labels: approved, size/M

#26 Remove Oauth Proxy
  grafana/prod/grafana.yaml
  grafana/prod/secret-generator.yaml
  grafana/prod/secrets/proxy_secret_grafana.enc.yaml
Labels: approved, size/M

#28 Add Blackbox monitoring for rsyslog
  prometheus/bases/blackbox/blackbox-prober-config.yaml
  prometheus/bases/blackbox/blackbox.yaml
  prometheus/bases/blackbox/kustomization.yaml
  prometheus/bases/blackbox/service.yaml
  prometheus/overlays/prod/kustomization.yaml
  prometheus/overlays/prod/prometheus/configs/additional-scrape-configs.yaml
Labels: approved, size/M

#24 Kustomize logstash
  .gitignore
  logstash/.sops.yaml
  logstash/README.md
  logstash/bases/admin_rolebindings/admin_rolebindings.yaml
  logstash/bases/admin_rolebindings/kustomization.yaml
  logstash/bases/logstash/argocd-manager-rolebinding.yaml
  logstash/bases/logstash/kustomization.yaml
  logstash/bases/logstash/logstash-conf/00-input-lumberjack.conf
  logstash/bases/logstash/logstash-conf/99-output-kafka.conf
  logstash/bases/logstash/logstash-conf/default
  logstash/bases/logstash/logstash-conf/logstash.yml
  logstash/bases/logstash/logstash.yaml
  logstash/bases/logstash/secrets/logstash-certs.enc.yaml
  logstash/bases/logstash/secrets/logstash-keys.enc.yaml
  logstash/bases/logstash/secrets/secret-generator.yaml
  logstash/bases/viewer_rolebindings/kustomization.yaml
  logstash/bases/viewer_rolebindings/viewer_rolebindings.yaml
  logstash/container-image/Dockerfile
  logstash/container-image/README.md
  logstash/container-image/build-image.sh
  logstash/container-image/install.sh
  logstash/container-image/log4j2.properties
  logstash/container-image/logstash.repo
  logstash/container-image/logstash.yml
  logstash/container-image/run-container.sh
  logstash/container-image/run.sh
  logstash/overlays/dev/kustomization.yaml
  logstash/overlays/dev/logstash.yaml
  logstash/overlays/prod/kustomization.yaml
  logstash/overlays/prod/logstash.yaml
  logstash/overlays/stage/kustomization.yaml
  logstash/overlays/stage/logstash.yaml
Labels: approved, size/XXL

#29 Move Alertmanager Routing Config to Secret
  prometheus/bases/alertmanager/config.yaml
  prometheus/bases/alertmanager/kustomization.yaml
  prometheus/overlays/prod/alertmanager/secrets/alertmanager-secret.enc.yaml
  prometheus/overlays/prod/secret-generator.yaml
Labels: approved, size/M

#31 Fix Prometheus Alerting
  prometheus/bases/prometheus/prometheus.yaml
Labels: approved, size/S

#32 Update target service for prometheus
  prometheus/bases/alertmanager/route.yaml
  prometheus/bases/alertmanager/service.yaml
  prometheus/bases/prometheus/prometheus.yaml
  prometheus/overlays/prod/alertmanager/patches/alertmanager.yaml
  rsyslog/overlays/prod/kustomization.yaml
  rsyslog/overlays/prod/rsyslog-prometheus-rule.yaml
Labels: approved, size/S

#33 Fix syntax error in rsyslog alerting rule
  rsyslog/overlays/prod/rsyslog-prometheus-rule.yaml
Labels: approved, size/XS
