Repository AICoE/internal-data-hub, pull requests merged in 2020-10, with the labels that each got.

#10 Reduce rsyslog memory to 1Gi
  rsyslog/overlays/prod/rsyslog.yaml
Labels: approved, size/XS

#11 Update ArgoCD rolebinding namespace
  rsyslog/bases/rsyslog/argocd-manager-rolebinding.yaml
Labels: approved, size/XS

#12 Add monitoring
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  grafana/.sops.yaml
  grafana/README.md
  grafana/prod/datasources/datasource.yaml
  grafana/prod/grafana.yaml
  grafana/prod/kustomization.yaml
  grafana/prod/secret-generator.yaml
  grafana/prod/secrets/proxy_secret_grafana.enc.yaml
  grafana/prod/secrets/router-ca.enc.yaml
  prometheus/.sops.yaml
  prometheus/README.md
  prometheus/bases/alertmanager/alertmanager.yaml
  prometheus/bases/alertmanager/config.yaml
  prometheus/bases/alertmanager/kustomization.yaml
  prometheus/bases/alertmanager/route.yaml
  prometheus/bases/alertmanager/service.yaml
  prometheus/bases/prometheus/kustomization.yaml
  prometheus/bases/prometheus/prometheus.yaml
  prometheus/bases/prometheus/route.yaml
  prometheus/bases/prometheus/service.yaml
  prometheus/overlays/prod/alertmanager/patches/alertmanager.yaml
  prometheus/overlays/prod/alertmanager/patches/route.yaml
  prometheus/overlays/prod/alertmanager/patches/service.yaml
  prometheus/overlays/prod/alertmanager/secrets/proxy_secret_alert_manager.enc.yaml
  prometheus/overlays/prod/kustomization.yaml
  prometheus/overlays/prod/oauth_client.yaml
  prometheus/overlays/prod/prometheus/configs/additional-scrape-configs.yaml
  prometheus/overlays/prod/prometheus/patches/prometheus.yaml
  prometheus/overlays/prod/prometheus/patches/route.yaml
  prometheus/overlays/prod/prometheus/patches/service.yaml
  prometheus/overlays/prod/prometheus/secrets/htpasswd_secret_prometheus.enc.yaml
  prometheus/overlays/prod/prometheus/secrets/proxy_secret_prometheus.enc.yaml
  prometheus/overlays/prod/router-ca/router-ca.enc.yaml
  prometheus/overlays/prod/secret-generator.yaml
  yamllint-config.yaml
Labels: approved, size/XL

#13 Fix linting errors for rsyslog
  rsyslog/container-image/Dockerfile
  rsyslog/container-image/rsyslog.conf
  rsyslog/container-image/run.sh
Labels: approved, size/S

#15 Remove duplicate router-ca in kustomization
  grafana/prod/secret-generator.yaml
Labels: approved, size/XS

#16 Add servicemonitor ns selector to prom
  prometheus/bases/prometheus/prometheus.yaml
Labels: approved, size/XS
