Repository AICoE/internal-data-hub, pull requests merged in 2021-07, with the labels that each got.

#64 Update kafka cert for rsyslog
  rsyslog/overlays/stage/secrets/kafka-cert.enc.yaml
Labels: approved, lgtm, size/M

#66 Update prod rsyslog cert for kafka
  rsyslog/overlays/prod/secrets/kafka-cert.enc.yaml
Labels: approved, lgtm, size/M

#67 Update Kafka keystores for Logstash
  logstash/overlays/prod/secrets/kafka-truststore-secret.enc.yaml
Labels: approved, lgtm, size/XS

#70 Fixed some issues from ArgoCD diff
  obslytics/bases/alert-template.yaml
  obslytics/bases/triggers.yaml
  obslytics/bases/workflow-templates.yaml
  obslytics/overlays/dev/workflow-templates.yaml
  obslytics/overlays/prod/obslytics-cron-workflow.yaml
  obslytics/overlays/prod/verification-cron-workflow.yaml
  obslytics/overlays/prod/workflow-templates.yaml
  obslytics/overlays/stage/workflow-templates.yaml
Labels: approved, size/M

#71 Remove updateStrategy from Obslytics Dataviz DC
  obslytics/bases/dataviz.yaml
Labels: approved, lgtm, size/XS

#72 Remove Obslytics Dataviz DC Image Spec, Add csv_succeeded metric
  obslytics/bases/dataviz.yaml
  obslytics/overlays/dev/dataviz.yaml
  obslytics/overlays/prod/dataviz.yaml
  obslytics/overlays/prod/triggers.yaml
  obslytics/overlays/stage/dataviz.yaml
Labels: approved, lgtm, size/S

#74 Change Obslytics Metrics List inputs to use withItems
  obslytics/bases/triggers.yaml
  obslytics/overlays/dev/triggers.yaml
  obslytics/overlays/prod/triggers.yaml
  obslytics/overlays/stage/triggers.yaml
Labels: approved, lgtm, size/L

#76 Reduce retryStrategy amount for cron workflow
  obslytics/overlays/prod/workflow-templates.yaml
Labels: approved, lgtm, size/XS

#77 Add lucferbux to owner list
  OWNERS
Labels: approved, lgtm, size/XS
