Repository AICoE/internal-data-hub, pull requests merged in 2021-11, with the labels that each got.

#142 Add instructions for monitoring services to README
  README.md
Labels: approved, size/S, lgtm

#143 Updated specs for the obslytics migration
  obslytics/overlays/ocp4-migration/backfill-cron-workflow.yaml
  obslytics/overlays/ocp4-migration/obslytics-cron-workflow.yaml
  obslytics/overlays/ocp4-migration/workflow-templates.yaml
  obslytics/overlays/prod/backfill-cron-workflow.yaml
  obslytics/overlays/prod/obslytics-cron-workflow.yaml
Labels: approved, size/S, lgtm

#144 Stop specifying standard for trino db pvc
  kfdefs/overlays/prod/dh-prod-trino/trino-db-pvc.yaml
Labels: approved, size/XS, lgtm

#145 Updatedd Obslytics Trigger Workflow to call Trino update-partition-metadata
  argo-workflows/base/kustomization.yaml
  argo-workflows/base/trino-workflow-templates.yaml
  argo-workflows/base/update-partition-metadata-workflow.yaml
  argo-workflows/overlays/prod/kustomization.yaml
  argo-workflows/overlays/prod/secret-generator.yaml
  argo-workflows/overlays/prod/trino-admin-credentials.enc.yaml
  argo-workflows/overlays/prod/update-partition-metadata-workflow_patch.yaml
  obslytics/bases/triggers.yaml
  obslytics/bases/workflow-templates.yaml
  obslytics/overlays/dev/secrets/obslytics-secret.enc.yaml
  obslytics/overlays/ocp4-migration/secrets/obslytics-secret.enc.yaml
  obslytics/overlays/prod/secrets/obslytics-secret.enc.yaml
  obslytics/overlays/stage/secrets/obslytics-secret.enc.yaml
Labels: approved, size/XL, lgtm

#146 Add secure Trino route for datahub ocp4 cluster
  kfdefs/overlays/prod/dh-prod-trino/trino-route.enc.yaml
Labels: approved, size/M, lgtm

#147 Add prod trino route to secret generator
  kfdefs/overlays/prod/dh-prod-trino/secret-generator.yaml
Labels: approved, size/XS, lgtm

#149 Bump Paralellism on OCP4 Obslytics ETL Pipelines
  obslytics/overlays/ocp4-migration/triggers.yaml
  obslytics/overlays/ocp4-migration/workflow-templates.yaml
Labels: approved, size/XS, lgtm

#150 Add kustomize objects for help.datahub
  datahub-help/.sops.yaml
  datahub-help/base/kustomization.yaml
  datahub-help/base/nodejs-image-stream.yaml
  datahub-help/base/secret-generator.yaml
  datahub-help/base/stasis-reactor-build-config.enc.yaml
  datahub-help/base/stasis-reactor-deployment-config.yaml
  datahub-help/base/stasis-reactor-image-stream.yaml
  datahub-help/base/stasis-reactor-route.yaml
  datahub-help/base/stasis-reactor-service.yaml
  datahub-help/overlays/dev/kustomization.yaml
  datahub-help/overlays/prod/kustomization.yaml
  datahub-help/overlays/prod/secret-generator.yaml
  datahub-help/overlays/prod/stasis-reactor-route.enc.yaml
  datahub-help/overlays/stage/kustomization.yaml
Labels: approved, size/L, lgtm

#152 Adjust Backfill Minimum Timestamp
  obslytics/bases/triggers.yaml
Labels: approved, size/XS, lgtm

#153 Enable Trino monitoring via UWM
  kfdefs/base/trino/kustomization.yaml
  kfdefs/base/trino/trino-service-monitor.yaml
  kfdefs/base/trino/trino-service.yaml
Labels: approved, size/S, lgtm

#156 Fixup triggers for dh-docs build
  datahub-help/base/dh-docs-trigger-secret.enc.yaml
  datahub-help/base/kustomization.yaml
  datahub-help/base/stasis-reactor-build-config.enc.yaml
Labels: approved, size/M, lgtm

#157 Fix sopsifying of dh-docs trigger secret
  datahub-help/.sops.yaml
  datahub-help/base/dh-docs-trigger-secret.enc.yaml
  datahub-help/base/kustomization.yaml
  datahub-help/base/secret-generator.yaml
Labels: approved, size/M, lgtm

#158 Change case of image change trigger to fix argocd diff
  datahub-help/base/dh-docs-trigger-secret.enc.yaml
  datahub-help/base/stasis-reactor-build-config.enc.yaml
Labels: approved, size/S, lgtm

#159 Fixup stashs-reactor buildconfig to not require encryption
  datahub-help/base/dh-docs-github-trigger-secret.enc.yaml
  datahub-help/base/dh-docs-trigger-secret.enc.yaml
  datahub-help/base/kustomization.yaml
  datahub-help/base/secret-generator.yaml
  datahub-help/base/stasis-reactor-build-config.enc.yaml
  datahub-help/base/stasis-reactor-build-config.yaml
Labels: approved, size/L, lgtm

#161 Add a service account for sandbox telemetry grafana
  telemetry-grafana/overlays/sandbox/data-foundation-pms-serviceaccount.yaml
  telemetry-grafana/overlays/sandbox/kustomization.yaml
Labels: approved, size/XS, lgtm

#160 Revert to encrypted buildconfig for docs
  datahub-help/base/dh-docs-github-trigger-secret.enc.yaml
  datahub-help/base/dh-docs-trigger-secret.enc.yaml
  datahub-help/base/kustomization.yaml
  datahub-help/base/secret-generator.yaml
  datahub-help/base/stasis-reactor-build-config.enc.yaml
  datahub-help/base/stasis-reactor-build-config.yaml
Labels: approved, size/L, lgtm

#162 Grant permissions to the SA for sandbox grafana
  telemetry-grafana/overlays/sandbox/kustomization.yaml
Labels: approved, size/S, lgtm

#163 Add blackbox exporter definition
  monitoring/base/blackbox-exporter.yaml
  monitoring/base/kustomization.yaml
  monitoring/overlays/dev/kustomization.yaml
  monitoring/overlays/prod/kustomization.yaml
  monitoring/overlays/stage/kustomization.yaml
Labels: approved, size/L, lgtm

#164 Remove Progressdeadlineseconds from BBOX Deployment Spec
  monitoring/base/blackbox-exporter.yaml
Labels: size/XS, lgtm

#165 Update the trino cert
  kfdefs/overlays/prod/dh-prod-trino/trino-route.enc.yaml
Labels: size/S, lgtm

#166 Add blackbox exporter
  kfdefs/base/trino/kustomization.yaml
  kfdefs/base/trino/trino-blackbox-service-monitor.yaml
  monitoring/.sops.yaml
  monitoring/base/blackbox-exporter.yaml
  monitoring/base/kustomization.yaml
  monitoring/base/rh-it-ca-certificate-secret.enc.yaml
  monitoring/base/secret-generator.yaml
Labels: approved, size/M, lgtm

#167 Add a route for the blackbox expoter
  monitoring/base/blackbox-exporter.yaml
Labels: approved, size/S, lgtm

#169 Fix CA certificate used by blackbox exporter
  monitoring/base/blackbox-exporter.yaml
  monitoring/base/rh-it-ca-certificate-secret.enc.yaml
Labels: approved, size/S, lgtm

#168 Add a blackbox service monitor probe for datahub help
  datahub-help/base/datahub-help-blackbox-service-monitor.yaml
  datahub-help/base/kustomization.yaml
Labels: approved, size/M, lgtm

#170 Move blackbox probes to monitoring kustomize directory
  datahub-help/base/kustomization.yaml
  kfdefs/base/trino/kustomization.yaml
  monitoring/base/datahub-help-blackbox-service-monitor.yaml
  monitoring/base/kustomization.yaml
  monitoring/base/trino-blackbox-service-monitor.yaml
Labels: approved, size/XS, lgtm

#171 Update RHODS to 1.2.0-2
  rhods/catalog-source/overlays/dev/catalog-source.yaml
  rhods/catalog-source/overlays/production/catalog-source.yaml
  rhods/catalog-source/overlays/stage/catalog-source.yaml
Labels: approved, size/XS, lgtm

#151 Mount trino certificate in Superset
  kfdefs/base/superset/kustomization.yaml
  kfdefs/base/superset/secret-generator.yaml
  kfdefs/base/superset/superset-deployment.yaml
  kfdefs/base/superset/trino-route-certificate-secret.enc.yaml
Labels: approved, size/M, lgtm

#172 Updated Trino Route in Obslytics Workflow
  obslytics/bases/workflow-templates.yaml
  obslytics/overlays/dev/secrets/obslytics-secret.enc.yaml
  obslytics/overlays/ocp4-migration/secrets/obslytics-secret.enc.yaml
  obslytics/overlays/prod/secrets/obslytics-secret.enc.yaml
  obslytics/overlays/stage/secrets/obslytics-secret.enc.yaml
Labels: approved, size/L, lgtm

#173 Add Blackbox Recording and Alerting rules
  monitoring/base/blackbox-alerting-rules.yaml
  monitoring/base/blackbox-recording-rules.yaml
  monitoring/base/kustomization.yaml
Labels: approved, size/M, lgtm

#174 Fix argocd for stage telemetry grafana
  telemetry-grafana/overlays/stage/grafana-cluster-role-binding.yaml
Labels: approved, size/XS, lgtm

#175 Fix datahubalert label in blackbox alerts to be 'boolean'
  monitoring/base/blackbox-alerting-rules.yaml
Labels: approved, size/XS, lgtm

#176 Increase Obslytics backfill count to 15
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/XS, lgtm

#177 Connect to Thanos with Trino
  kfdefs/base/trino/kustomization.yaml
  kfdefs/base/trino/secret-generator.yaml
  kfdefs/base/trino/trino-catalog-secret.enc.yaml
  kfdefs/base/trino/trino-config-secret.yaml
  kfdefs/base/trino/trino-coordinator-dc.yaml
  kfdefs/base/trino/trino-jvm-coordinator-config.enc.yaml
  kfdefs/base/trino/trino-jvm-worker-config.enc.yaml
  kfdefs/base/trino/trino-telemetry-sa-token.enc.yaml
  kfdefs/base/trino/trino-truststore.enc.yaml
  kfdefs/base/trino/trino-worker-dc.yaml
  kfdefs/overlays/prod/dh-prod-trino/kustomization.yaml
  kfdefs/overlays/prod/dh-prod-trino/trino-config-secret.yaml
Labels: approved, size/L, lgtm

#180 Add iceberg connector to Trino
  kfdefs/base/trino/trino-catalog-secret.enc.yaml
  kfdefs/base/trino/trino-coordinator-dc.yaml
  kfdefs/base/trino/trino-worker-dc.yaml
Labels: approved, size/S, lgtm

#181 fix the hive connector configuration
  kfdefs/base/trino/trino-catalog-secret.enc.yaml
Labels: approved, size/XS, lgtm

#182 Add Ceph Cert to Trino Truststore
  kfdefs/base/trino/trino-truststore.enc.yaml
Labels: approved, size/XS, lgtm

#183 Fix Obslytics dataviz on OCP4
  obslytics/overlays/ocp4-migration/secrets/obslytics-secret.enc.yaml
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/M

#185 Upgrade RHODS to version 1.3
  rhods/catalog-source/overlays/dev/catalog-source.yaml
  rhods/catalog-source/overlays/production/catalog-source.yaml
  rhods/catalog-source/overlays/stage/catalog-source.yaml
Labels: approved, size/XS, lgtm
