Repository AICoE/internal-data-hub, pull requests merged in 2021-09, with the labels that each got.

#86 Add user that has permissions to pull backups of supersetDB
  kfdefs/overlays/prod/dh-prod-superset/kustomization.yaml
  kfdefs/overlays/prod/dh-prod-superset/superset-db-secret.enc.yaml
  kfdefs/overlays/prod/dh-prod-superset/supersetdb-deployment-pvc-backup.yaml
Labels: approved, size/M, lgtm

#87 Add route and NodePort for supersetdb service
  kfdefs/overlays/prod/dh-prod-superset/kustomization.yaml
  kfdefs/overlays/prod/dh-prod-superset/supersetdb-route.yaml
  kfdefs/overlays/prod/dh-prod-superset/supersetdb-service-nodePort.yaml
Labels: approved, lgtm

#88 Change upstream base commit to add monitoring on Trino
  kfdefs/base/trino/kustomization.yaml
  kfdefs/base/trino/trino-config-secret.yaml
  kfdefs/base/trino/trino-coordinator-dc.yaml
Labels: approved, size/S, lgtm

#89 Add prometheus Service monitor for trino
  prometheus/overlays/prod/service-monitors/kustomization.yaml
  prometheus/overlays/prod/service-monitors/trino-service-monitor.yaml
Labels: approved, size/S, lgtm

#90 Add new ccx and ccx_sensitive ACL configuration and new memory limit …
  kfdefs/base/trino/trino-config-secret.yaml
Labels: size/S, lgtm

#91 Add superset secured route and set superset session to 6 hours
  kfdefs/base/superset/superset-config-secret.yaml
  kfdefs/overlays/prod/dh-prod-superset/secret-generator.yaml
  kfdefs/overlays/prod/dh-prod-superset/superset-secured-route.enc.yaml
Labels: approved, size/M

#92 Add missed query memory limits in Trino worker configuration
  kfdefs/base/trino/trino-config-secret.yaml
Labels: size/XS

#93 Increase Superset route timeout for long-running Trino queries
  kfdefs/overlays/prod/dh-prod-superset/superset-secured-route.enc.yaml
Labels: approved, size/XS

#94 set timeout for Superset Webserver to 30 minutes
  kfdefs/base/superset/superset-config-secret.yaml
Labels: approved, size/XS

#95 Add ACL for cost-management team and fix CCX ACL rules
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/S, lgtm

#96 Add ccx-admin permissions to hive catalog
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#97 Add Admin rolebinding for Data-Hub OpenShift Admins
  components/project-admin-rolebindings/data-hub/kustomization.yaml
  components/project-admin-rolebindings/data-hub/rbac.yaml
Labels: approved, size/S, lgtm

#98 Add DASHBOARD_RBAC feature flag in Superset
  kfdefs/base/superset/superset-config-secret.yaml
Labels: approved, size/XS, lgtm

#100 Copy RHODS installation artifacts from internal repo to GitHub
  rhods/README.md
  rhods/catalog-source/.sops.yaml
  rhods/catalog-source/base/catalog-source.yaml
  rhods/catalog-source/base/kustomization.yaml
  rhods/catalog-source/base/secrets/modh-idh-cluster-image-puller-secret.enc.yaml
  rhods/catalog-source/base/secrets/secret-generator.yaml
  rhods/catalog-source/base/service-account.yaml
  rhods/catalog-source/overlays/stage/catalog-source.yaml
  rhods/catalog-source/overlays/stage/kustomization.yaml
  rhods/ods-applications/.sops.yaml
  rhods/ods-applications/base/kustomization.yaml
  rhods/ods-applications/base/namespace.yaml
  rhods/ods-applications/base/secrets/addon-managed-odh-pullsecret.enc.yaml
  rhods/ods-applications/base/secrets/secret-generator.yaml
  rhods/ods-applications/overlays/stage/kustomization.yaml
  rhods/ods-monitoring/.sops.yaml
  rhods/ods-monitoring/base/kustomization.yaml
  rhods/ods-monitoring/base/namespace.yaml
  rhods/ods-monitoring/base/secrets/redhat-rhods-deadmanssnitch.enc.yaml
  rhods/ods-monitoring/base/secrets/redhat-rhods-pagerduty-secret.enc.yaml
  rhods/ods-monitoring/base/secrets/secret-generator.yaml
  rhods/ods-monitoring/overlays/stage/kustomization.yaml
  rhods/rhods/.sops.yaml
  rhods/rhods/base/addon-managed-odh.yaml
  rhods/rhods/base/kustomization.yaml
  rhods/rhods/base/namespace.yaml
  rhods/rhods/base/redhat-layer-product-og.yaml
  rhods/rhods/base/secrets/addon-managed-odh-pullsecret.enc.yaml
  rhods/rhods/base/secrets/secret-generator.yaml
  rhods/rhods/overlays/stage/kustomization.yaml
Labels: approved, size/L, lgtm
