Repository AICoE/internal-data-hub, pull requests merged in 2021-10, with the labels that each got.

#101 Fix ACL configuration for CCX and cost-management teams
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/S, lgtm

#104 Comment the DASHBOARD_RBAC flag in Superset until 1.3.0 upgrade
  kfdefs/base/superset/superset-config-secret.yaml
Labels: approved, size/XS

#106 Add skamired to trino telemetry group
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#107 Move RHODS Catalog Source to redhat-ods-operator namespace
  rhods/catalog-source/base/kustomization.yaml
  rhods/catalog-source/overlays/production/catalog-source.yaml
  rhods/ods-operator/privileged/addon-managed-odh.yaml
Labels: approved, size/XS

#108 Fix permissions for backup user on superset database
  kfdefs/overlays/prod/dh-prod-superset/supersetdb-deployment-pvc-backup.yaml
Labels: approved, size/XS, lgtm

#113 Route RHODS alerts to IDH team pagerduty
  rhods/ods-monitoring/base/secrets/redhat-rhods-pagerduty-secret.enc.yaml
  rhods/ods-monitoring/overlays/production/kustomization.yaml
  rhods/ods-monitoring/overlays/production/secrets/pagerduty-secret.enc.yaml
  rhods/ods-monitoring/overlays/production/secrets/secret-generator.yaml
Labels: approved, size/M, lgtm

#116 Remove extra sandbox grafana route
  telemetry-grafana/overlays/sandbox/grafana-sandbox-route.yaml
  telemetry-grafana/overlays/sandbox/kustomization.yaml
Labels: approved, size/S, lgtm

#121 Replace int with string in kustomize
  kfdefs/overlays/prod/dh-prod-superset/kustomization.yaml
Labels: approved, size/XS, lgtm

#123 Remove the storage class from supersetdb pvc
  kfdefs/overlays/stage/dh-stage-superset/supersetdb-pvc.yaml
Labels: approved, size/XS, lgtm

#128 Remote unused ImageChange trigger from Obslytics BCs
  obslytics/bases/images.yaml
Labels: approved, size/XS, lgtm

#131 Update docker registry location for ocp4 Obslytics WorkflowTemplates
  obslytics/overlays/ocp4-migration/workflow-templates.yaml
Labels: approved, size/S, lgtm

#136 Add additional users to the telemetry trino group
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm
