Repository AICoE/internal-data-hub, pull requests merged in 2021-12, with the labels that each got.

#186 Update superset storageclass for new ocp4 cluster
  kfdefs/overlays/prod/dh-prod-superset/kustomization.yaml
Labels: approved, size/XS, lgtm

#184 Obslytics metrics metadata
  obslytics/bases/kustomization.yaml
  obslytics/bases/obslytics-cron-workflow.yaml
  obslytics/bases/triggers.yaml
  obslytics/bases/workflow-templates.yaml
  obslytics/overlays/dev/kustomization.yaml
  obslytics/overlays/dev/obslytics-cron-workflow.yaml
  obslytics/overlays/dev/triggers.yaml
  obslytics/overlays/ocp4-migration/backfill-cron-workflow.yaml
  obslytics/overlays/ocp4-migration/kustomization.yaml
  obslytics/overlays/ocp4-migration/obslytics-cron-workflow.yaml
  obslytics/overlays/ocp4-migration/triggers.yaml
  obslytics/overlays/prod/kustomization.yaml
  obslytics/overlays/prod/obslytics-cron-workflow.yaml
  obslytics/overlays/prod/triggers.yaml
  obslytics/overlays/stage/kustomization.yaml
  obslytics/overlays/stage/obslytics-cron-workflow.yaml
  obslytics/overlays/stage/triggers.yaml
Labels: approved, size/XL, lgtm

#188 Obslytics metrics add
  obslytics/overlays/ocp4-migration/triggers.yaml
  obslytics/overlays/ocp4-migration/workflow-templates.yaml
Labels: approved

#191 Remove unnessary gap_detector script overlay
  obslytics/overlays/ocp4-migration/workflow-templates.yaml
  obslytics/overlays/prod/workflow-templates.yaml
  obslytics/overlays/stage/workflow-templates.yaml
Labels: size/M, lgtm

#187 Add blackbox probe for superset.datahub.redhat.com
  monitoring/base/kustomization.yaml
  monitoring/base/superset-blackbox-service-monitor.yaml
Labels: approved, size/M, lgtm

#192 Add additional telemetry group role mappings
  kfdefs/base/superset/superset-config-secret.yaml
Labels: size/XS, lgtm

#193 Add more resources to dh-prod-trino nodes
  kfdefs/overlays/prod/dh-prod-trino/kustomization.yaml
  kfdefs/overlays/prod/dh-prod-trino/trino-coordinator-dc.yaml
Labels: approved, size/S, lgtm

#194 Scale up the right Trino deployment
  kfdefs/overlays/prod/dh-prod-trino/kustomization.yaml
  kfdefs/overlays/prod/dh-prod-trino/trino-worker-dc.yaml
Labels: approved, size/S, lgtm

#195 Moving replicas attribute to the right location
  kfdefs/overlays/prod/dh-prod-trino/trino-worker-dc.yaml
Labels: approved, size/S, lgtm

#196 Add more memory to Trino cluster/Set Query memory parameters
  kfdefs/overlays/prod/dh-prod-trino/kustomization.yaml
  kfdefs/overlays/prod/dh-prod-trino/trino-config-secret.yaml
Labels: approved, size/S, lgtm

#197 Fix Query memory parameters
  kfdefs/overlays/prod/dh-prod-trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#199 Add access to users to dhcuratedhive schema
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/S, lgtm

#201 Add anti-affinity rules to trino worker pods
  kfdefs/base/trino/trino-worker-dc.yaml
Labels: approved, size/S, lgtm

#202 Set anti-affinity rule for trino worker pods only
  kfdefs/base/trino/trino-worker-dc.yaml
Labels: approved, size/XS

#203 Upgrade rhods to 1.4.0-2
  rhods/catalog-source/overlays/dev/catalog-source.yaml
  rhods/catalog-source/overlays/production/catalog-source.yaml
  rhods/catalog-source/overlays/stage/catalog-source.yaml
Labels: approved, size/XS, lgtm

#204 Change hive connector name to the latest connector version
  kfdefs/base/trino/trino-catalog-secret.enc.yaml
Labels: approved, size/XS, lgtm

#206 Grant wpinheir user to USIR trino schema
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#205 Override trino cluster size for dev
  kfdefs/overlays/dev/dh-dev-trino/aws-secret.enc.yaml
  kfdefs/overlays/dev/dh-dev-trino/kustomization.yaml
  kfdefs/overlays/dev/dh-dev-trino/secret-generator.yaml
  kfdefs/overlays/dev/dh-dev-trino/trino-config-secret.yaml
  kfdefs/overlays/dev/dh-dev-trino/trino-worker-dc.yaml
Labels: approved, size/L, lgtm

#209 Add new recent metrics, adjust backfill count to accommodate
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/M

#210 Bump up backfill amount
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/XS, lgtm

#208 Enable oauth for Superset
  kfdefs/base/superset/kustomization.yaml
  kfdefs/base/superset/superset-deployment.yaml
  kfdefs/base/superset/superset_additional_config.py
  kfdefs/base/superset/superset_config.py
Labels: approved, size/L, lgtm

#211 Upgrade superset to 1.3.0
  kfdefs/overlays/prod/dh-prod-superset/kustomization.yaml
Labels: approved, size/XS

#212 Add prod redirect reference for superset service account
  kfdefs/overlays/prod/dh-prod-superset/kustomization.yaml
  kfdefs/overlays/prod/dh-prod-superset/superset-service-account.yaml
Labels: approved, size/XS, lgtm

#213 Adjust backfill cutoff times and count
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/M

#214 Add more obslytics metrics
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: size/M, lgtm
