Repository AICoE/internal-data-hub, pull requests merged in 2021-06, with the labels that each got.

#52 Fix Trino Admin credentials secret
  argo-workflows/overlays/prod/trino-admin-credentials.enc.yaml
Labels: approved, lgtm, size/XS

#53 Change TRINO_HOST value in trino secret
  argo-workflows/overlays/prod/trino-admin-credentials.enc.yaml
Labels: approved, lgtm, size/XS

#54 Fix TRINO_HOST env var in secret
  argo-workflows/overlays/prod/trino-admin-credentials.enc.yaml
Labels: approved, lgtm, size/XS

#55 Add Trino kustomize descriptors using upstream ODH
  kfdefs/.sops.yaml
  kfdefs/base/trino/aws-secret.enc.yaml
  kfdefs/base/trino/kfdef.yaml
  kfdefs/base/trino/kustomization.yaml
  kfdefs/base/trino/root-ca-secret.enc.yaml
  kfdefs/base/trino/secret-generator.yaml
  kfdefs/base/trino/trino-db-secret.enc.yaml
  kfdefs/overlays/dev/dh-dev-trino/kustomization.yaml
  kfdefs/overlays/dev/kustomization.yaml
  kfdefs/overlays/prod/dh-prod-trino/kustomization.yaml
  kfdefs/overlays/prod/kustomization.yaml
  kfdefs/overlays/stage/dh-stage-trino/kustomization.yaml
  kfdefs/overlays/stage/kustomization.yaml
  odh-manifests/README.md
  odh-manifests/trino/base/hive-config.yaml
  odh-manifests/trino/base/trino-config-secret.yaml
  odh-manifests/trino/base/trino-coordinator-dc.yaml
  odh-manifests/trino/base/trino-db-pvc.yaml
Labels: approved, lgtm, size/XL

#57 Change path to upstream ODH to use a remote ref
  kfdefs/base/trino/kustomization.yaml
  odh-manifests/trino/base/trino-config-secret.yaml
Labels: approved, lgtm, size/XS

#58 Set missing parameters for stage
  kfdefs/overlays/stage/dh-stage-trino/kustomization.yaml
Labels: approved, lgtm, size/S

#60 update the resource limit for the prowjobs
  .prow.yaml
  argo-workflows/base/trino-workflow-templates.yaml
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, lgtm, size/S

#61 Fix deployment for dh-prod-trino
  kfdefs/base/trino/trino-config-secret.yaml
  kfdefs/overlays/prod/dh-prod-trino/kustomization.yaml
Labels: approved, size/XS

#62 Add PVC for dh-prod-trino to keep in sync with first deployment
  kfdefs/overlays/prod/dh-prod-trino/kustomization.yaml
Labels: approved, lgtm, size/XS

#63 Add ACL configuration for USIR group and schema
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, lgtm, size/S
