Repository AICoE/internal-data-hub, pull requests merged in 2021-03, with the labels that each got.

#40 Replace .aicoe.yaml with .prow.yaml
  .aicoe-ci.yaml
  .prow.yaml
  test-kustomize-build
Labels: approved, size/M

#41 Add Kafka keystores for Logstash
  logstash/overlays/prod/kustomization.yaml
  logstash/overlays/prod/logstash.yaml
  logstash/overlays/prod/secrets/kafka-truststore-secret.enc.yaml
  logstash/overlays/prod/secrets/secret-generator.yaml
  logstash/overlays/stage/kustomization.yaml
  logstash/overlays/stage/logstash.yaml
  logstash/overlays/stage/secrets/kafka-truststore-secret.enc.yaml
  logstash/overlays/stage/secrets/secret-generator.yaml
Labels: approved, lgtm, size/M

#42 Fix Keystore Mount Path
  logstash/overlays/prod/logstash.yaml
  logstash/overlays/stage/logstash.yaml
Labels: approved, size/XS

#43 Add truststore secret to overlay
  logstash/bases/logstash/logstash.yaml
  logstash/overlays/dev/kustomization.yaml
  logstash/overlays/dev/logstash.yaml
  logstash/overlays/dev/secrets/kafka-truststore-secret.enc.yaml
  logstash/overlays/dev/secrets/secret-generator.yaml
  logstash/overlays/prod/logstash.yaml
  logstash/overlays/stage/logstash.yaml
Labels: approved, size/M

#44 Configure stage logstash to use kafka external route
  logstash/bases/logstash/logstash.yaml
  logstash/container-image/Dockerfile
  logstash/overlays/stage/kustomization.yaml
  logstash/overlays/stage/logstash-conf/99-output-kafka.conf
  logstash/overlays/stage/logstash.yaml
  logstash/overlays/stage/secrets/kafka-truststore-secret.enc.yaml
Labels: approved, lgtm, size/M

#45 Configure production logstash to send to kafka via external route
  logstash/overlays/prod/kustomization.yaml
  logstash/overlays/prod/logstash-conf/99-output-kafka.conf
  logstash/overlays/prod/logstash.yaml
  logstash/overlays/prod/secrets/kafka-truststore-secret.enc.yaml
Labels: approved, lgtm, size/M

#46 Add log4j2.properties in /etc/logstash
  logstash/bases/logstash/kustomization.yaml
  logstash/bases/logstash/logstash-conf/log4j2.properties
Labels: approved, lgtm, size/S

#47 Add truststore and security protocol for sending to Kafka
  logstash/bases/logstash/logstash.yaml
  logstash/overlays/prod/logstash-conf/99-output-kafka.conf
  logstash/overlays/prod/secrets/kafka-truststore-secret.enc.yaml
  logstash/overlays/stage/logstash-conf/99-output-kafka.conf
  logstash/overlays/stage/secrets/kafka-truststore-secret.enc.yaml
Labels: approved, size/M

#48 Add truststore password
  logstash/overlays/prod/logstash-conf/99-output-kafka.conf
  logstash/overlays/prod/logstash.yaml
  logstash/overlays/prod/secrets/kafka-truststore-secret.enc.yaml
  logstash/overlays/stage/logstash-conf/99-output-kafka.conf
  logstash/overlays/stage/logstash.yaml
  logstash/overlays/stage/secrets/kafka-truststore-secret.enc.yaml
Labels: approved, lgtm, size/M

#49 Update kafka topic for rsyslog
  rsyslog/bases/rsyslog/rsyslog-conf/50-kafka-output.conf
Labels: approved, lgtm, size/XS
