Repository AICoE/internal-data-hub, pull requests merged in 2022-01, with the labels that each got.

#216 Add users to usir group/Grant ccx-admin read-only access to telemetry…
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/S, lgtm

#219 Add deployment for superset bareos-fd pod
  kfdefs/overlays/prod/dh-prod-superset/bareos-fd-deploymentconfig.yaml
  kfdefs/overlays/prod/dh-prod-superset/bareos-fd-imagestream.yaml
  kfdefs/overlays/prod/dh-prod-superset/kustomization.yaml
Labels: approved, size/M, lgtm

#220 Add bareos-config secret
  kfdefs/overlays/prod/dh-prod-superset/bareos-fd-config-secret.enc.yaml
  kfdefs/overlays/prod/dh-prod-superset/bareos-fd-deploymentconfig.yaml
  kfdefs/overlays/prod/dh-prod-superset/secret-generator.yaml
Labels: approved, size/M

#221 Replace "data" with "stringData" in bareos config secret
  kfdefs/overlays/prod/dh-prod-superset/bareos-fd-config-secret.enc.yaml
Labels: approved, size/XS

#215 Adjust Obslytics backfill_to values
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/L

#223 Run each 'size' of obslytics pod in its own phase
  obslytics/bases/triggers.yaml
  obslytics/overlays/dev/triggers.yaml
  obslytics/overlays/dev/workflow-templates.yaml
  obslytics/overlays/ocp4-migration/triggers.yaml
  obslytics/overlays/prod/triggers.yaml
  obslytics/overlays/prod/workflow-templates.yaml
  obslytics/overlays/stage/triggers.yaml
  obslytics/overlays/stage/workflow-templates.yaml
Labels: approved, size/XL, lgtm

#225 Change trino-worker anti affinity rule
  kfdefs/base/trino/trino-worker-dc.yaml
Labels: approved, size/XS

#226 Enable Obslytics first-batch small metrics
  obslytics/bases/triggers.yaml
  obslytics/bases/workflow-templates.yaml
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/L, lgtm

#227 Adjust Obslytics backfill parameters
  obslytics/bases/workflow-templates.yaml
  obslytics/overlays/ocp4-migration/triggers.yaml
  obslytics/overlays/ocp4-migration/workflow-templates.yaml
Labels: size/S, lgtm

#228 Adjust Obslytics Backfill amount
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/XS, lgtm

#229 Dont block if previous phase fails
  obslytics/bases/triggers.yaml
  obslytics/bases/workflow-templates.yaml
  obslytics/overlays/ocp4-migration/workflow-templates.yaml
  obslytics/overlays/prod/triggers.yaml
Labels: size/S

#230 Increment obslytics backfill count
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: size/XS

#231 More Obslytics adjustments
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: size/XS

#232 Adjust backfill count
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: size/XS

#233 Change Obslytics concurrencyPolicy to Replace
  obslytics/bases/backfill-cron-workflow.yaml
  obslytics/bases/verification-cron-workflow.yaml
Labels: approved, size/XS, lgtm

#234 Update kustomize base for superset
  kfdefs/base/superset/kustomization.yaml
Labels: approved, size/XS, lgtm

#235 Fix Trino Partition Metadata updater to use self-signed Trino certs
  obslytics/bases/workflow-templates.yaml
Labels: approved, size/XS, lgtm

#236 Add service for superset bareos backup
  kfdefs/overlays/prod/dh-prod-superset/bareos-fd-service.yaml
  kfdefs/overlays/prod/dh-prod-superset/kustomization.yaml
Labels: approved, size/S, lgtm

#237 Upgrade rhods to 1.5.0-7
  rhods/catalog-source/overlays/dev/catalog-source.yaml
  rhods/catalog-source/overlays/production/catalog-source.yaml
  rhods/catalog-source/overlays/stage/catalog-source.yaml
Labels: approved, size/XS, lgtm

#238 Fix typo in rhods catalog source
  rhods/catalog-source/overlays/dev/catalog-source.yaml
  rhods/catalog-source/overlays/production/catalog-source.yaml
  rhods/catalog-source/overlays/stage/catalog-source.yaml
Labels: approved, size/XS, lgtm

#239 Update RHODS to 1.5.0-7 with custom index image
  rhods/catalog-source/overlays/dev/catalog-source.yaml
  rhods/catalog-source/overlays/production/catalog-source.yaml
  rhods/catalog-source/overlays/stage/catalog-source.yaml
Labels: approved, size/XS

#240 Remove Maulik from OWNERS list
  OWNERS
Labels: approved, size/XS, lgtm

#241 Scale Down backfill count
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/XS, lgtm
