Repository AICoE/internal-data-hub, pull requests merged in 2022-09, with the labels that each got.

#453 Grant the TAM group access to telemetry grafana
  telemetry-grafana/base/telemeter-groups-rolebinding.yaml
Labels: size/XS

#454 Update trino docs to reflect use of LDAP group provider
  Makefile
  README.md
Labels: size/L

#455 Add new ccx_internal schema
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/XS, ok-to-test

#456 Update s3-webserver CVP s3 credentials
  s3-webserver/base/secret.enc.yaml
Labels: approved, size/XS, lgtm
