Repository AICoE/internal-data-hub, pull requests merged in 2022-04, with the labels that each got.

#305 Adjust backfill count parameter allow for intervention-less recovery from outage
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: size/XS, lgtm

#306 Re-enable large-scale obslytics backfill parameters
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/XS, lgtm

#308 Update our RHODS deployment to version 1.9.0-7
  rhods/catalog-source/base/catalog-source.yaml
Labels: approved, size/XS

#309 Grant the assisted-lakers LDAP group both CCX Superset roles
  kfdefs/base/superset/superset_additional_config.py
Labels: approved, size/XS, lgtm

#310 Add assisted-lakers group with access to ccx and ccx sensitive Trino schemas
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#311 Bump up ingestion rate for small obslytics metrics
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/XS, lgtm

#312 Obslytics: Move 'up' label to large metrics step
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/XS, lgtm

#315 Add trino group for CCX access requests
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#316 Add some error handling for Obslytics Partition Metadata updater
  obslytics/bases/triggers.yaml
  obslytics/bases/workflow-templates.yaml
Labels: approved, size/M, lgtm

#317 Update obslytics metadata print statement to conform to python version
  obslytics/bases/workflow-templates.yaml
Labels: approved, size/XS, lgtm

#318 Add aravindh to CCX trino group
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#319 Introduce new batch of Large Obslytics metrics
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/M, lgtm

#322 Increase Superset database storage limit to 5GB
  kfdefs/overlays/prod/dh-prod-superset/kustomization.yaml
Labels: approved, size/S

#323 Fix syntax for Superset database storage
  kfdefs/overlays/prod/dh-prod-superset/kustomization.yaml
Labels: approved, size/XS

#324 Fix pvc size syntax
  kfdefs/overlays/prod/dh-prod-superset/kustomization.yaml
Labels: approved, size/XS

#325 Add jholecek to ccx trino group
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#321 Use Quay for argo-tools image
  obslytics/bases/alert-template.yaml
  obslytics/overlays/ocp4-migration/alert-template.yaml
  obslytics/overlays/ocp4-migration/kustomization.yaml
Labels: approved, size/S, lgtm

#326 Outage recovery: Comment out active backfill metrics, remove retrySt…
  obslytics/overlays/ocp4-migration/triggers.yaml
  obslytics/overlays/ocp4-migration/workflow-templates.yaml
Labels: size/M, lgtm
