Repository AICoE/internal-data-hub, pull requests merged in 2022-05, with the labels that each got.

#328 Add additional users to ccx datalake access for Trino
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS

#330 Fix s3 backup secret and add readme and triggers
  argo-workflows/README.md
  argo-workflows/base/s3-backup-pipeline-cron-workflows.yaml
  argo-workflows/overlays/dev/secrets/s3-backup-pipeline-secrets.yaml
  argo-workflows/overlays/prod/secrets/s3-backup-pipeline-secrets.yaml
  argo-workflows/triggers/s3-backup-parameterized-trigger.yaml
Labels: approved, size/L

#331 Update s3 backup image to pull from quay
  argo-workflows/base/s3-backup-pipeline-cron-workflows.yaml
Labels: approved, size/XS

#314 Adding minio dependencies required for KFP
  kfp-tekton/overlays/dev/configmaps/kfp-tekton-config.yaml
  kfp-tekton/overlays/dev/deployments/minio.yaml
  kfp-tekton/overlays/dev/deployments/ml-pipeline-ui.yaml
  kfp-tekton/overlays/dev/kustomization.yaml
  kfp-tekton/overlays/dev/persistentvolumeclaims/minio-pvc.yaml
  kfp-tekton/overlays/dev/secrets/mlpipeline-minio-artifact.yaml
  kfp-tekton/overlays/dev/services/minio-service.yaml
Labels: approved, size/L, lgtm

#332 Post-Outage: Re-add new batch Obslytics metrics
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: size/M, lgtm

#335 Add blackbox service monitors for cvp s3 webserver and telemetry grafana
  monitoring/base/cvp-s3-webserver-blackbox-service-monitor.yaml
  monitoring/base/kustomization.yaml
  monitoring/base/telemeter-lts-dashboards-blackbox-service-monitor.yaml
Labels: approved, size/M, lgtm

#336 Upgrade RHODS install to version 1.10.0-6
  rhods/catalog-source/base/catalog-source.yaml
Labels: approved, size/XS, lgtm

#338 Revert "Rever RHODS to version 1.9"
  rhods/catalog-source/base/catalog-source.yaml
Labels: size/XS, lgtm

#341 Add s3 syncs for floorist and cost management
  argo-workflows/base/secrets/cost-management-sync-secret.enc.yaml
  argo-workflows/base/secrets/floorist-sync-secret.enc.yaml
  argo-workflows/base/secrets/secret-generator.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/kustomization.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-cost-management-cron-workflow.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-floorist-cron-workflow.yaml
Labels: approved, size/L, lgtm

#304 Change commit hash in superset base for superset 1.4.1 upgrade
  kfdefs/base/superset/kustomization.yaml
Labels: approved, size/XS, lgtm

#342 Add s3 sync job for IBM marketplace data
  argo-workflows/base/secrets/marketplace2ibm-sync-secret.enc.yaml
  argo-workflows/base/secrets/marketplace2psi-sync-secret.enc.yaml
  argo-workflows/base/secrets/secret-generator.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/kustomization.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-markeplace2ibm-cron-workflow.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-markeplace2psi-cron-workflow.yaml
Labels: approved, size/L, lgtm

#343 Update workflow schedules
  argo-workflows/overlays/prod/backup-cron-workflows/s3-backup-cpaas.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-backup-marketplace-metering.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-backup-thanos-obslytics.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-cost-management-cron-workflow.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-floorist-cron-workflow.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-markeplace2ibm-cron-workflow.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-markeplace2psi-cron-workflow.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-rhods-usage-metrics-cron-workflow.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-rhods-usage-metrics-dev-cron-workflow.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-tower-analytics-cron-workflow.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-tower-analytics-stage-cron-workflow.yaml
Labels: approved, size/S

#344 Add s3 sync job for stage usir data
  argo-workflows/base/secrets/secret-generator.yaml
  argo-workflows/base/secrets/usir-stage-sync-secret.enc.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/kustomization.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-usir-stage-cron-workflow.yaml
Labels: approved, size/M, lgtm

#346 Setup CCX-SREP group in Trino config
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/S, lgtm

#347 Add Insights Trino Group config
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/S

#348 Add eda-admin Service Account and eda group with global read permissions
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/S, lgtm

#350 Fix Trino SSL certificates
  kfdefs/overlays/prod/dh-prod-trino/trino-route.enc.yaml
Labels: approved, size/XS, lgtm

#351 Add erjones and mleonard to the requested groups
  kfdefs/base/trino/trino-config-secret.yaml
Labels: size/XS

#355 Add RHODS-PXE (Product Experience Engineers) Trino Group
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm
