Repository AICoE/internal-data-hub, pull requests merged in 2022-08, with the labels that each got.

#415 Add new user to digests tables
  kfdefs/base/trino/trino-group-mapping.properties
Labels: approved, size/XS, ok-to-test

#416 Update all of our trino groups from ldap
  kfdefs/base/trino/trino-group-mapping.properties
Labels: approved, size/S, lgtm

#417 feat: Add ACL rules for new mustgather schema 'mg_rules_data'
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/S, ok-to-test

#419 Grant telemetry-edmun-abbot access to ccx data in Trino
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/XS, lgtm

#421 Update trino group membership
  kfdefs/base/trino/trino-group-mapping.properties
Labels: approved, size/S, lgtm

#418 Add instructions for updating Trino ACLs
  README.md
Labels: size/L, lgtm

#422 Fix access to telemetry grafana
  telemetry-grafana/base/grafana-deploymentconfig.yaml
  telemetry-grafana/overlays/dev/kustomization.yaml
  telemetry-grafana/overlays/prod/kustomization.yaml
  telemetry-grafana/overlays/sandbox/kustomization.yaml
  telemetry-grafana/overlays/stage/kustomization.yaml
Labels: approved, size/M, lgtm

#424 Update trino groups from LDAP
  kfdefs/base/trino/trino-group-mapping.properties
Labels: approved

#429 Set trino config parameters using env vars
  kfdefs/base/trino/trino-config-secret.yaml
  kfdefs/base/trino/trino-coordinator-dc.yaml
  kfdefs/base/trino/trino-worker-dc.yaml
  kfdefs/overlays/dev/dh-dev-trino/kustomization.yaml
  kfdefs/overlays/dev/dh-dev-trino/secret-generator.yaml
  kfdefs/overlays/dev/dh-dev-trino/trino-config-env-settings-secret.enc.yaml
  kfdefs/overlays/dev/dh-dev-trino/trino-config-secret.yaml
  kfdefs/overlays/prod/dh-prod-trino/kustomization.yaml
  kfdefs/overlays/prod/dh-prod-trino/secret-generator.yaml
  kfdefs/overlays/prod/dh-prod-trino/trino-config-env-settings-secret.enc.yaml
  kfdefs/overlays/prod/dh-prod-trino/trino-config-secret.yaml
  kfdefs/overlays/stage/dh-stage-trino/kustomization.yaml
  kfdefs/overlays/stage/dh-stage-trino/secret-generator.yaml
  kfdefs/overlays/stage/dh-stage-trino/trino-config-env-settings-secret.enc.yaml
  kfdefs/overlays/stage/dh-stage-trino/trino-config-secret.yaml
Labels: size/L, lgtm

#428 Use the development image for stage trino
  kfdefs/overlays/stage/dh-stage-trino/kustomization.yaml
Labels: size/XS

#427 Update cost-management trino group with cost-management-team
  Makefile
  kfdefs/base/trino/trino-acl-rules.json
  kfdefs/base/trino/trino-group-mapping.properties
Labels: lgtm

#430 Configure stage to use the ldap group provider
  kfdefs/base/trino/secret-generator.yaml
  kfdefs/base/trino/trino-coordinator-dc.yaml
  kfdefs/base/trino/trino-ldap-settings-secret.enc.yaml
  kfdefs/overlays/dev/dh-dev-trino/trino-config-env-settings-secret.enc.yaml
  kfdefs/overlays/prod/dh-prod-trino/trino-config-env-settings-secret.enc.yaml
  kfdefs/overlays/stage/dh-stage-trino/kustomization.yaml
  kfdefs/overlays/stage/dh-stage-trino/trino-config-env-settings-secret.enc.yaml
Labels: size/M, lgtm

#435 Upgrade superset to version 1.5 in dev and stage
  kfdefs/overlays/dev/dh-dev-superset/kustomization.yaml
  kfdefs/overlays/stage/dh-stage-superset/kustomization.yaml
Labels: approved, size/S, lgtm

#436 Increase size of stage superset pvc
  kfdefs/overlays/stage/dh-stage-superset/supersetdb-pvc.yaml
Labels: size/XS

#438 Replace trino groups for accessing insighs_*_analytics data
  Makefile
  kfdefs/base/trino/trino-acl-rules.json
  kfdefs/base/trino/trino-group-mapping.properties
Labels: approved, size/S, lgtm

#431 Use rover groups for usir access
  Makefile
  kfdefs/base/trino/trino-acl-rules.json
  kfdefs/base/trino/trino-group-mapping.properties
Labels: approved, size/S, lgtm

#439 Add LDAP group provider for prod trino
  kfdefs/base/trino/kustomization.yaml
  kfdefs/base/trino/trino-config-secret.yaml
  kfdefs/base/trino/trino-group-mapping.properties
  kfdefs/overlays/stage/dh-stage-trino/kustomization.yaml
Labels: approved, size/M

#440 Add access for superset ccx service users
  kfdefs/base/trino/trino-acl-rules.json
Labels: size/S

#442 Allow the trino-admin user to impersonate any user in trino
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved

#443 Add CA cert for stage trino to superset deployment
  kfdefs/base/superset/trino-route-certificate-secret.enc.yaml
Labels: approved, size/XS

#445 Grant impersonation permissions to new superset user
  kfdefs/base/trino/trino-acl-rules.json
Labels: size/XS

#446 Remove unused trino service users
  kfdefs/base/trino/trino-service-accounts-passwords.db
Labels: size/XS

#447 Upgrade superset to version 1.5.0
  kfdefs/base/superset/kustomization.yaml
  kfdefs/overlays/stage/dh-stage-superset/kustomization.yaml
Labels: size/S, lgtm

#450 Allow all users to read from system.metadata tables
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/XS, lgtm

#451 Update sa permissions for trino
  kfdefs/base/trino/trino-acl-rules.json
  kfdefs/base/trino/trino-service-accounts-passwords.db
Labels: size/S

#452 Add LDAP group provider for prod trino (#439)
  kfdefs/base/trino/kustomization.yaml
  kfdefs/base/trino/trino-config-secret.yaml
  kfdefs/base/trino/trino-group-mapping.properties
  kfdefs/overlays/stage/dh-stage-trino/kustomization.yaml
Labels: size/M, lgtm
