Repository AICoE/internal-data-hub, pull requests merged in 2022-07, with the labels that each got.

#376 Grant CCX Trino access (+ sensitive) to cblum
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, needs-ok-to-test

#377 Add certificates for superset and telemeter-lts-dashboard hostnames
  kfdefs/overlays/prod/dh-prod-superset/superset-secured-route.enc.yaml
  telemetry-grafana/overlays/prod/grafana-external-route.enc.yaml
Labels: approved, size/S, lgtm

#378 Add telemetry-emund-abbot service account for Trino
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#383 Update permissions for trino catalogs
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#384 Update the Trino ACLs every 30 seconds
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#385 Fix case of parquetreads3 schema
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#386 Fix access for new superset insights users
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#387 Fix insights-admins trino access
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#389 Configure user and group files to automatically refresh
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#390 Add akandel to trino ccx-sensitive group
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#391 Grant mashaikh access to ccx trino data
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#392 Add a superset user to Trino
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#393 Add adi to ccx trino groups
  kfdefs/base/trino/trino-config-secret.yaml
Labels: size/XS, lgtm

#395 Add additional CCX users
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#396 Update insights permissions for superset user impersonation
  kfdefs/base/trino/trino-config-secret.yaml
Labels: size/XS, lgtm

#397 Add tnovotny as our newest CCX Analytics member
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, ok-to-test

#398 Add tuhsharm to ccx data viewers
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS

#399 Add new rhel-insights trino groups
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/S, lgtm

#401 Move Trino acl definitions out to separate files
  kfdefs/base/trino/kustomization.yaml
  kfdefs/base/trino/trino-acl-rules.json
  kfdefs/base/trino/trino-config-secret.yaml
  kfdefs/base/trino/trino-coordinator-dc.yaml
  kfdefs/base/trino/trino-group-mapping.properties
  kfdefs/base/trino/trino-service-accounts-passwords.db
Labels: do-not-merge/hold, size/L, lgtm

#403 Fix trino acls secret mount
  kfdefs/base/trino/trino-coordinator-dc.yaml
Labels: approved, size/XS, lgtm

#405 Update Trino truststore with new Ceph s3 cert
  kfdefs/base/trino/trino-truststore.enc.yaml
Labels: approved, size/XS, lgtm

#406 Fix authorization to telemetry grafana
  telemetry-grafana/base/grafana-deploymentconfig.yaml
Labels: approved, size/XS, lgtm

#408 Actually fix the telemetry grafana access
  telemetry-grafana/base/grafana-deploymentconfig.yaml
Labels: approved, size/XS, lgtm

#404 Generate Trino group mapping
  Makefile
  kfdefs/base/trino/trino-group-mapping.properties
Labels: size/M, ok-to-test

#410 Revert "Actually fix the telemetry grafana access"
  telemetry-grafana/base/grafana-deploymentconfig.yaml
Labels: size/XS

#409 Add more RHEL Insights Trino viewers
  kfdefs/base/trino/trino-group-mapping.properties
Labels: approved, size/XS, ok-to-test

#402 Set trino permissions for cide-must-gather insights groups
  kfdefs/base/trino/trino-acl-rules.json
  kfdefs/base/trino/trino-group-mapping.properties
Labels: approved, size/S, lgtm

#411 Update Makefile to work for generic LDAP groups
  Makefile
  README.md
  kfdefs/base/trino/trino-group-mapping.properties
Labels: approved, size/S, lgtm

#412 Added syncing of Trino access for ccx-dev group
  Makefile
  kfdefs/base/trino/trino-acl-rules.json
  kfdefs/base/trino/trino-group-mapping.properties
Labels: approved, size/S, ok-to-test

#413 Update trino group membership and access rules
  Makefile
  kfdefs/base/trino/trino-acl-rules.json
  kfdefs/base/trino/trino-group-mapping.properties
Labels: approved, size/S, lgtm

#414 Add trino groups for ccx superset access
  Makefile
  kfdefs/base/trino/trino-acl-rules.json
  kfdefs/base/trino/trino-group-mapping.properties
Labels: approved, size/M, lgtm
