Repository AICoE/internal-data-hub, pull requests merged in 2022-02, with the labels that each got.

#242 Add Grafana Operator Deployment artifacts
  grafana/base/kustomization.yaml
  grafana/base/subscription.yaml
  grafana/overlays/dev/kustomization.yaml
  grafana/overlays/dev/operator-group.yaml
  grafana/overlays/prod/kustomization.yaml
  grafana/overlays/prod/operator-group.yaml
  grafana/overlays/stage/kustomization.yaml
  grafana/overlays/stage/operator-group.yaml
Labels: approved, size/M, lgtm

#243 Add Grafana deployment objects
  grafana/base/configs/ldap.toml
  grafana/base/grafana.yaml
  grafana/base/kustomization.yaml
  grafana/base/secret-generator.yaml
  grafana/base/secrets/admin_credentials.enc.yaml
  grafana/overlays/prod/kustomization.yaml
  grafana/overlays/prod/privileged/operator-group.yaml
Labels: approved, size/L, lgtm

#244 Add Router Certificate Bundle
  grafana/base/grafana.yaml
  grafana/overlays/prod/kustomization.yaml
  grafana/overlays/prod/secret-generator.yaml
  grafana/overlays/prod/secrets/router-ca.enc.yaml
Labels: approved, size/M, lgtm

#246 Add next batch of Obslytics metrics
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/M, lgtm

#247 Upgrade rhods catalog source to 1.6.0-8
  rhods/catalog-source/overlays/dev/catalog-source.yaml
  rhods/catalog-source/overlays/production/catalog-source.yaml
  rhods/catalog-source/overlays/stage/catalog-source.yaml
Labels: approved, size/XS, lgtm

#245 Camel k integration
  camelk/README.md
  camelk/base/integration-platform.yaml
  camelk/base/kustomization.yaml
  camelk/base/subscription.yaml
  camelk/overlays/dev/kustomization.yaml
  camelk/overlays/dev/operator-group.yaml
  camelk/overlays/prod/kustomization.yaml
  camelk/overlays/prod/privileged/operator-group.yaml
  camelk/overlays/stage/kustomization.yaml
  camelk/overlays/stage/operator-group.yaml
Labels: approved, size/M, lgtm

#249 Add thanos-querier as data source
  grafana/.sops.yaml
  grafana/overlays/prod/secret-generator.yaml
  grafana/overlays/prod/secrets/data-source.enc.yaml
Labels: approved, size/M, lgtm

#251 Change Obslytics concurrencyPolicy to Allow
  obslytics/bases/backfill-cron-workflow.yaml
  obslytics/bases/verification-cron-workflow.yaml
Labels: approved, size/XS, lgtm

#252 Reduce scheduling frequency of backfill pipeline
  obslytics/overlays/ocp4-migration/backfill-cron-workflow.yaml
Labels: approved, size/XS, lgtm

#253 Changed camel k operator to community edition
  camelk/base/integration-platform.yaml
  camelk/base/subscription.yaml
Labels: approved, size/XS, lgtm

#254 Changed name of camel k operator
  camelk/base/subscription.yaml
Labels: approved, size/XS, lgtm

#255 Rearrange Obslytics Small Metric Parallism
  obslytics/bases/workflow-templates.yaml
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: size/XS, lgtm

#256 Enable monitoring for all Camel-K objects
  camelk/base/integration-platform.yaml
Labels: approved, size/XS, lgtm

#257 Reduce kafka usage
  kfdefs/base/kafka/kafka-cluster.yaml
  kfdefs/overlays/prod/dh-prod-message-bus/kafka-cluster.yaml
Labels: size/S, lgtm

#258 Add kustomize artifacts for deploying s3 webserver
  s3-webserver/.sops.yaml
  s3-webserver/base/buildconfig.yaml
  s3-webserver/base/configmap.yaml
  s3-webserver/base/deploymentconfig.yaml
  s3-webserver/base/imagestream.yaml
  s3-webserver/base/kustomization.yaml
  s3-webserver/base/routes.yaml
  s3-webserver/base/secret-generator.yaml
  s3-webserver/base/secret.enc.yaml
  s3-webserver/base/service.yaml
  s3-webserver/overlays/dev/kustomization.yaml
  s3-webserver/overlays/prod/kustomization.yaml
  s3-webserver/overlays/stage/kustomization.yaml
Labels: approved, size/L, lgtm

#259 Fix S3 Backup Util Secret Name
  argo-workflows/base/s3-backup-pipeline-cron-workflows.yaml
Labels: approved, size/S, lgtm

#260 Add kafka2trino integration to camelk
  camelk/.sops.yaml
  camelk/base/kafka2trino.yaml
  camelk/base/kustomization.yaml
  camelk/overlays/dev/kafka-properties.yaml
  camelk/overlays/dev/kustomization.yaml
  camelk/overlays/dev/secret-generator.yaml
  camelk/overlays/dev/secrets/kafka-properties.enc.yaml
  camelk/overlays/dev/secrets/kafka2trino-truststore.enc.yaml
  camelk/overlays/dev/secrets/trino-beans.enc.yaml
  camelk/overlays/prod/kustomization.yaml
  camelk/overlays/prod/secret-generator.yaml
  camelk/overlays/prod/secrets/kafka-properties.enc.yaml
  camelk/overlays/prod/secrets/kafka2trino-truststore.enc.yaml
  camelk/overlays/prod/secrets/trino-beans.enc.yaml
  camelk/overlays/stage/kustomization.yaml
  camelk/overlays/stage/operator-group.yaml
Labels: approved, size/L, lgtm

#261 Specify full api for s3-webserver resources
  s3-webserver/base/buildconfig.yaml
  s3-webserver/base/deploymentconfig.yaml
  s3-webserver/base/imagestream.yaml
  s3-webserver/base/routes.yaml
Labels: approved, size/S, lgtm

#263 Fix syntax of s3 webserver memory limit
  s3-webserver/base/deploymentconfig.yaml
Labels: size/XS

#264 Remove alerting rule for rsyslog
  prometheus/overlays/prod/alerting-rules/kustomization.yaml
  prometheus/overlays/prod/alerting-rules/rsyslog-prometheus-rules.yaml
Labels: approved, size/S, lgtm

#266 Add kfp tekton kustomize manifests
  kfp-tekton/.sops.yaml
  kfp-tekton/base/ceph-artifact.enc.yaml
  kfp-tekton/base/kfp-tekton-config.yaml
  kfp-tekton/base/kustomization.yaml
  kfp-tekton/base/secret-generator.yaml
  kfp-tekton/overlays/dev/kustomization.yaml
  kfp-tekton/overlays/prod/kustomization.yaml
  kfp-tekton/overlays/stage/kustomization.yaml
Labels: approved, size/L, lgtm

#267 Specify group name for kafka2trino consumer
  camelk/overlays/prod/secrets/kafka-properties.enc.yaml
Labels: size/S, lgtm

#268 Refactor Trino kustomize to scale worker replicas
  kfdefs/overlays/prod/dh-prod-trino/kustomization.yaml
  kfdefs/overlays/prod/dh-prod-trino/trino-worker-dc.yaml
Labels: approved, size/S, lgtm

#269 Increase backfill job frequency
  obslytics/overlays/ocp4-migration/backfill-cron-workflow.yaml
Labels: size/XS, lgtm

#270 Add Camel-K GrafanaDashboard
  grafana/overlays/prod/dashboards/camelk-dashboard.yaml
  grafana/overlays/prod/dashboards/kustomization.yaml
  grafana/overlays/prod/kustomization.yaml
Labels: approved, size/XXL, lgtm

#271 Remove CustomFolderName and name fields from Camel-k grafana dashboar…
  grafana/overlays/prod/dashboards/camelk-dashboard.yaml
Labels: approved, size/XS

#272 Enable Superset Dashboard RBAC
  kfdefs/overlays/stage/dh-stage-superset/kustomization.yaml
  kfdefs/overlays/stage/dh-stage-superset/superset_additional_config.py
Labels: approved, size/L, lgtm

#273 Update stage superset resources to match prod
  kfdefs/overlays/stage/dh-stage-superset/kustomization.yaml
Labels: approved, size/S, lgtm

#274 Add More Obslytics Metrics to Backfill
  obslytics/overlays/ocp4-migration/backfill-cron-workflow.yaml
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/M, lgtm

#276 Upgrade RHODS to version 1.7
  rhods/catalog-source/base/catalog-source.yaml
  rhods/catalog-source/overlays/dev/catalog-source.yaml
  rhods/catalog-source/overlays/dev/kustomization.yaml
  rhods/catalog-source/overlays/production/catalog-source.yaml
  rhods/catalog-source/overlays/production/kustomization.yaml
  rhods/catalog-source/overlays/stage/catalog-source.yaml
  rhods/catalog-source/overlays/stage/kustomization.yaml
Labels: approved, size/S, lgtm

#277 Enable filter flags
  kfdefs/overlays/stage/dh-stage-superset/superset_additional_config.py
Labels: approved, size/XS, lgtm

#278 Attempt to fix programmatic API access for telemetry grafana
  telemetry-grafana/base/grafana-deploymentconfig.yaml
  telemetry-grafana/overlays/stage/grafana-cluster-role-binding.yaml
Labels: approved, size/XS

#279 Move telemetry-grafana stage role binding to privileged folder
  telemetry-grafana/overlays/stage/kustomization.yaml
  telemetry-grafana/overlays/stage/privileged/grafana-cluster-role-binding.yaml
Labels: approved, size/XS
