Repository AICoE/internal-data-hub, pull requests merged in 2022-10, with the labels that each got.

#458 Add access to obfuscated data
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/S, ok-to-test

#457 Add cs-csa-auto-ccx access to CCX data
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/XS, lgtm, ok-to-test

#460 Add subscription-watch-ro to usir Trino schema
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/XS
