Repository AICoE/internal-data-hub, pull requests merged in 2022-03, with the labels that each got.

#280 Disable filter sets as they are not yet stable
  kfdefs/overlays/stage/dh-stage-superset/superset_additional_config.py
Labels: approved, size/XS, lgtm

#281 Enable new Superset feature flags for all environments
  kfdefs/base/superset/superset_additional_config.py
  kfdefs/overlays/stage/dh-stage-superset/kustomization.yaml
  kfdefs/overlays/stage/dh-stage-superset/superset_additional_config.py
Labels: approved, size/L, lgtm

#284 Add scale-writers property in Trino
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#285 Bump up obslytics ingestion, disable problematic metric
  obslytics/overlays/ocp4-migration/backfill-cron-workflow.yaml
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/XS, lgtm

#286 Update kfp-tekton kustomize with latest commit
  kfp-tekton/base/ceph-artifact.enc.yaml
  kfp-tekton/base/kustomization.yaml
Labels: approved, size/S, lgtm

#283 Convert kafka2trino integration to Java
  camelk/base/kafka2trino.yaml
  camelk/overlays/prod/secrets/trino-beans.enc.yaml
Labels: approved, size/M, lgtm

#287 Update Camel-K dashboard gauges
  grafana/overlays/prod/dashboards/camelk-dashboard.yaml
Labels: approved, size/S

#288 Bump Trino to release 371
  kfdefs/base/trino/kustomization.yaml
  kfdefs/overlays/dev/dh-dev-trino/trino-config-secret.yaml
  kfdefs/overlays/prod/dh-prod-trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#289 Update kfp-tekton with latest commit
  kfp-tekton/base/kustomization.yaml
Labels: approved, size/XS

#291 Revert the scale-writers configuration in Trino
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#290 Added pgoti to usir group in trino def
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#292 Add TAM groups to the CCX Sensitive role
  kfdefs/base/superset/superset_additional_config.py
Labels: approved, size/XS, lgtm

#295 Update token for telemetry grafana thanos datasource
  telemetry-grafana/base/grafana-datasources-secret.enc.yaml
Labels: approved, size/S, lgtm

#296 Upgrade RHODS to 1.8.0-14
  rhods/catalog-source/base/catalog-source.yaml
Labels: approved, size/XS, lgtm

#297 Grant all Telemetry groups the CCX role in Superset
  kfdefs/base/superset/superset_additional_config.py
Labels: approved, size/XS, lgtm

#299 Add new batch of Obslytics metrics
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/M

#298 More superset role changes for CCX team
  kfdefs/base/superset/superset_additional_config.py
Labels: approved, size/M, lgtm

#300 Update ODH base for Superset
  kfdefs/base/superset/kustomization.yaml
Labels: approved, size/XS

#294 Add a blackbox probe for jupyterhub
  monitoring/base/jupyterhub-blackbox-service-monitor.yaml
  monitoring/base/kustomization.yaml
Labels: approved, size/M, lgtm

#301 Move some larger obslytics metrics to large phase and stage for enablement
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/S, lgtm

#302 Add cblum to Telemetry trino group
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm
