Repository AICoE/internal-data-hub, pull requests merged in 2022-11, with the labels that each got.

#459 Add telemeter-auth for ccx_sensitive access
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/XS, ok-to-test

#461 adding readonly user for ccx tables
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/XS, ok-to-test

#462 feat: Setting group permissions for "sos_rules_data" schema
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/S, ok-to-test

#463 Add a blackbox probe for telemeter-lts
  monitoring/base/kustomization.yaml
  monitoring/base/telemeter-lts-blackbox-service-monitor.yaml
Labels: size/M
