Repository AICoE/internal-data-hub, pull requests merged in 2022-06, with the labels that each got.

#356 Give kfyfe access to CCX data: https://redhat.service-now.com/surl.do\?n\=TASK1261744
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#357 Add akoshlak to ccx-sensitive-datalake-access Trino group
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#358 Add ireyes to ccx team
  kfdefs/base/trino/trino-config-secret.yaml
Labels: size/XS, lgtm

#359 Renew datahub-help Route Cert
  datahub-help/overlays/prod/stasis-reactor-route.enc.yaml
Labels: approved, size/S, lgtm

#360 Enable XL Obslytics metrics
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/M, lgtm

#361 Add special access to Superset and Trino systems
  kfdefs/base/superset/superset_additional_config.py
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/S

#362 Adjust XL Metrics Obslytics Backfill Paramters
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/XS, lgtm

#363 Update sync creds for stage usir
  argo-workflows/base/secrets/usir-stage-sync-secret.enc.yaml
Labels: size/XS, lgtm

#364 Grant CCX Trino access to kmamgain
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#366 Grant CCX Trino access to shzhou
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#365 Actually use stage creds for usir stage sync
  argo-workflows/base/secrets/usir-stage-sync-secret.enc.yaml
Labels: size/XS

#367 Add s3 sync for usir prod data
  argo-workflows/base/s3-backup-workflow-template.yaml
  argo-workflows/base/secrets/secret-generator.yaml
  argo-workflows/base/secrets/usir-prod-sync-secret.enc.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/kustomization.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-usir-prod-cron-workflow.yaml
Labels: approved, lgtm

#368 Fix Trino ACL configuration
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#369 Obslytics: Bump XL memspec to 32Gi, move metric to xl list
  obslytics/bases/workflow-templates.yaml
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/XS

#370 Fix ACL issues and increase hive-metastore resources
  kfdefs/base/superset/superset_additional_config.py
  kfdefs/base/trino/trino-config-secret.yaml
  kfdefs/overlays/prod/dh-prod-trino/kustomization.yaml
Labels: approved, size/S

#372 Add Dharmit as a reviewer
  OWNERS
Labels: approved, size/XS, lgtm

#373 Obslytics: Comment out OOMKilling XL metrics and update note
  obslytics/overlays/ocp4-migration/triggers.yaml
Labels: approved, size/S

#374 Providing Trino access
  kfdefs/base/trino/trino-config-secret.yaml
Labels: approved, size/XS, lgtm
