Repository AICoE/internal-data-hub, pull requests merged in 2023-08, with the labels that each got.

#548 Grant asr-insights-dashboards group access to CCX data
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/XS, ok-to-test

#554 Remove prow
  .github/workflows/automerge.yaml
  .prow.yaml
Labels: approved, size/M

#555 Run automerge check after check run completed
  .github/workflows/automerge.yaml
Labels: size/XS

#558 Stop producing obslytics data
  obslytics/bases/triggers.yaml
  obslytics/overlays/dev/kustomization.yaml
  obslytics/overlays/dev/triggers.yaml
  obslytics/overlays/prod/kustomization.yaml
  obslytics/overlays/prod/triggers.yaml
Labels: approved

#560 Specify namespace for trino-partition-updater crb
  trino-partition-updater/overlays/prod/privileged/trino-partition-updater-eventlistener-clusterrolebinding.yaml
Labels: approved
