Repository AICoE/internal-data-hub, pull requests merged in 2023-02, with the labels that each got.

#489 Adding access to CCX data to CEE associates
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/XS, ok-to-test

#490 Fix pre-commit tests
  datahub-help/base/stasis-reactor-build-config.enc.yaml
Labels: size/XS

#491 Change RHODS deployment method to use self-managed
  rhods/catalog-source/.sops.yaml
  rhods/catalog-source/base/catalog-source.yaml
  rhods/catalog-source/base/kustomization.yaml
  rhods/catalog-source/base/secrets/modh-idh-cluster-image-puller-secret.enc.yaml
  rhods/catalog-source/base/secrets/secret-generator.yaml
  rhods/catalog-source/overlays/dev/kustomization.yaml
  rhods/catalog-source/overlays/production/kustomization.yaml
  rhods/catalog-source/overlays/stage/kustomization.yaml
  rhods/common/.sops.yaml
  rhods/common/kustomization.yaml
  rhods/common/secrets/modh-reader-secret.enc.yaml
  rhods/common/secrets/secret-generator.yaml
  rhods/ods-applications/.sops.yaml
  rhods/ods-applications/base/kustomization.yaml
  rhods/ods-applications/overlays/dev/kustomization.yaml
  rhods/ods-applications/overlays/production/kustomization.yaml
  rhods/ods-applications/overlays/stage/kustomization.yaml
  rhods/ods-applications/privileged/kustomization.yaml
  rhods/ods-applications/privileged/namespace.yaml
  rhods/ods-monitoring/.sops.yaml
  rhods/ods-monitoring/base/kustomization.yaml
  rhods/ods-monitoring/base/redhat-rhods-smtp-secret.yaml
  rhods/ods-monitoring/base/secrets/redhat-rhods-deadmanssnitch.enc.yaml
  rhods/ods-monitoring/base/secrets/redhat-rhods-pagerduty-secret.enc.yaml
  rhods/ods-monitoring/base/secrets/secret-generator.yaml
  rhods/ods-monitoring/overlays/dev/kustomization.yaml
  rhods/ods-monitoring/overlays/production/kustomization.yaml
  rhods/ods-monitoring/overlays/production/secrets/pagerduty-secret.enc.yaml
  rhods/ods-monitoring/overlays/production/secrets/secret-generator.yaml
  rhods/ods-monitoring/overlays/stage/kustomization.yaml
  rhods/ods-monitoring/privileged/kustomization.yaml
  rhods/ods-monitoring/privileged/namespace.yaml
  rhods/ods-operator/base/addon-managed-odh-parameters-secret.yaml
  rhods/ods-operator/base/addon-managed-odh.yaml
  rhods/ods-operator/base/kustomization.yaml
  rhods/ods-operator/base/rhods-operator-subscription.yaml
Labels: size/L

#492 Delete rhods-usage-metrics sync jobs
  argo-workflows/base/backup-cron-workflows/kustomization.yaml
  argo-workflows/base/backup-cron-workflows/s3-backup-testing-cron-workflow.yaml
  argo-workflows/base/kustomization.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/kustomization.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-rhods-usage-metrics-cron-workflow.yaml
  argo-workflows/overlays/prod/backup-cron-workflows/s3-sync-rhods-usage-metrics-dev-cron-workflow.yaml
Labels: size/M

#493 Upgrade sandbox telemetry grafana to version 9.3.6
  telemetry-grafana/overlays/sandbox/kustomization.yaml
Labels: size/XS

#494 Upgrade stage telemetry grafana to 9.3.6
  telemetry-grafana/overlays/stage/kustomization.yaml
Labels: size/XS

#495 Upgrade telemetry grafana to 9.3.6
  telemetry-grafana/base/grafana-deploymentconfig.yaml
  telemetry-grafana/overlays/sandbox/kustomization.yaml
  telemetry-grafana/overlays/stage/kustomization.yaml
Labels: size/S

#496 Remove access to telemetry dh curated schema
  kfdefs/base/trino/trino-acl-rules.json
Labels: size/S

#498 Remove deployment artifacts for things we don't care about
  camelk/.sops.yaml
  camelk/README.md
  camelk/base/integration-platform.yaml
  camelk/base/kafka2trino.yaml
  camelk/base/kustomization.yaml
  camelk/base/subscription.yaml
  camelk/overlays/dev/kafka-properties.yaml
  camelk/overlays/dev/kustomization.yaml
  camelk/overlays/dev/operator-group.yaml
  camelk/overlays/dev/secret-generator.yaml
  camelk/overlays/dev/secrets/kafka-properties.enc.yaml
  camelk/overlays/dev/secrets/kafka2trino-truststore.enc.yaml
  camelk/overlays/dev/secrets/trino-beans.enc.yaml
  camelk/overlays/prod/kustomization.yaml
  camelk/overlays/prod/privileged/operator-group.yaml
  camelk/overlays/prod/secret-generator.yaml
  camelk/overlays/prod/secrets/kafka-properties.enc.yaml
  camelk/overlays/prod/secrets/kafka2trino-truststore.enc.yaml
  camelk/overlays/prod/secrets/trino-beans.enc.yaml
  components/project-admin-rolebindings/data-hub/kustomization.yaml
  components/project-admin-rolebindings/data-hub/rbac.yaml
  kfdefs/base/kafka/kafka-cluster.yaml
  kfdefs/base/kafka/kafka-operator-service.yaml
  kfdefs/base/kafka/kustomization.yaml
  kfdefs/overlays/dev/dh-dev-message-bus/kafka-topics.yaml
  kfdefs/overlays/dev/dh-dev-message-bus/kustomization.yaml
  kfdefs/overlays/dev/kustomization.yaml
  kfdefs/overlays/prod/dh-prod-message-bus/kafka-cluster.yaml
  kfdefs/overlays/prod/dh-prod-message-bus/kafka-topics.yaml
  kfdefs/overlays/prod/dh-prod-message-bus/kustomization.yaml
  kfdefs/overlays/prod/kustomization.yaml
  kfdefs/overlays/stage/dh-stage-message-bus/kafka-cluster.yaml
  kfdefs/overlays/stage/dh-stage-message-bus/kafka-topics.yaml
  kfdefs/overlays/stage/dh-stage-message-bus/kustomization.yaml
  kfdefs/overlays/stage/kustomization.yaml
  kfp-tekton/.sops.yaml
  kfp-tekton/base/ceph-artifact.enc.yaml
  kfp-tekton/base/kfp-tekton-config.yaml
  kfp-tekton/base/kustomization.yaml
  kfp-tekton/base/secret-generator.yaml
  kfp-tekton/overlays/dev/configmaps/kfp-tekton-config.yaml
  kfp-tekton/overlays/dev/deployments/minio.yaml
  kfp-tekton/overlays/dev/deployments/ml-pipeline-ui.yaml
  kfp-tekton/overlays/dev/kustomization.yaml
  kfp-tekton/overlays/dev/persistentvolumeclaims/minio-pvc.yaml
  kfp-tekton/overlays/dev/secrets/mlpipeline-minio-artifact.yaml
  kfp-tekton/overlays/dev/services/minio-service.yaml
  kfp-tekton/overlays/prod/kustomization.yaml
  kfp-tekton/overlays/stage/kustomization.yaml
Labels: size/XXL

#499 Remove trino iceberg and prometheus catalogs
  kfdefs/base/trino/trino-catalog-secret.enc.yaml
  kfdefs/base/trino/trino-coordinator-dc.yaml
Labels: size/S
