Repository AICoE/internal-data-hub, pull requests merged in 2023-04, with the labels that each got.

#519 Update creds for s3 webserver
  s3-webserver/base/secret.enc.yaml
Labels: size/S

#522 Add trino schema rhel_reference_data
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/S, ok-to-test

#523 Add new trino SA for IBM research team
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/S, ok-to-test

#526 Remove s3 syncs that are no longer needed
  s3-sync-pipelines/overlays/prod/secrets/cost-management-sync-secret.enc.yaml
  s3-sync-pipelines/overlays/prod/secrets/datahub-s3-backup-secret.enc.yaml
  s3-sync-pipelines/overlays/prod/secrets/marketplace2ibm-sync-secret.enc.yaml
  s3-sync-pipelines/overlays/prod/secrets/marketplace2psi-sync-secret.enc.yaml
  s3-sync-pipelines/overlays/prod/secrets/secret-generator.yaml
  s3-sync-pipelines/overlays/prod/sync-instances/cost-management.yaml
  s3-sync-pipelines/overlays/prod/sync-instances/kustomization.yaml
  s3-sync-pipelines/overlays/prod/sync-instances/marketplace2ibm.yaml
  s3-sync-pipelines/overlays/prod/sync-instances/marketplace2psi.yaml
  s3-sync-pipelines/overlays/prod/sync-instances/marketplacemetering.yaml
Labels: size/L

#525 Add new ccx_workloads schema
  kfdefs/base/superset/superset_additional_config.py
  kfdefs/base/trino/trino-acl-rules.json
Labels: approved, size/M, ok-to-test
